<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class DocumentFieldMapping extends Model
{
    protected $fillable = [
        'vendus_field',
        'vendus_field_label',
        'metadata_key',
        'field_type',
        'is_required',
        'default_value',
        'description',
        'is_active',
    ];

    protected $casts = [
        'is_required' => 'boolean',
        'is_active' => 'boolean',
    ];

    /**
     * Retorna todos os mapeamentos ativos
     */
    public static function getMappedFields()
    {
        return self::where('is_active', true)->orderBy('vendus_field')->get();
    }

    /**
     * Cria mapeamentos padrão de faturas
     */
    public static function createDefaultMappings(): void
    {
        $defaults = [
            [
                'vendus_field' => 'store_title',
                'vendus_field_label' => 'Loja - Nome',
                'metadata_key' => 'Marca',
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Nome da loja para resolver store_id',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'register_title',
                'vendus_field_label' => 'Caixa - Título',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Nome do caixa para resolver register_id',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'type',
                'vendus_field_label' => 'Tipo do Documento',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Tipo (FT, FS, FR, NC, RG, etc.)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'discount_code',
                'vendus_field_label' => 'Código de Desconto',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Código de desconto do documento',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'discount_amount',
                'vendus_field_label' => 'Desconto (Valor)',
                'metadata_key' => null,
                'field_type' => 'number',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Desconto do documento em valor (€)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'discount_percentage',
                'vendus_field_label' => 'Desconto (Percentual)',
                'metadata_key' => null,
                'field_type' => 'number',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Desconto do documento em percentagem (%)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'date_due',
                'vendus_field_label' => 'Data de Vencimento',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Data de vencimento (YYYY-MM-DD)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'mode',
                'vendus_field_label' => 'Modo',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Modo de emissão (ex.: normal)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'document_number',
                'vendus_field_label' => 'Número do Documento',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Número/Chave para agrupar linhas da mesma fatura (opcional)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'series',
                'vendus_field_label' => 'Série',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Série de numeração da fatura',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'customer_name',
                'vendus_field_label' => 'Cliente - Nome',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => true,
                'default_value' => 'Consumidor final',
                'description' => 'Nome do cliente',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'customer_nif',
                'vendus_field_label' => 'Cliente - NIF',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Número de contribuinte (NIF)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'date',
                'vendus_field_label' => 'Data do Documento',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Data da fatura (YYYY-MM-DD)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'date_supply',
                'vendus_field_label' => 'Data de Fornecimento',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Data de fornecimento/serviço (YYYY-MM-DD)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'notes',
                'vendus_field_label' => 'Notas',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Observações adicionais',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'ncr_id',
                'vendus_field_label' => 'NCR ID',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Identificador específico (quando aplicável)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'external_reference',
                'vendus_field_label' => 'Referência Externa',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Referência externa do documento',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'stock_operation',
                'vendus_field_label' => 'Operação de Stock',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Operação de stock (out/in)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'ifthenpay',
                'vendus_field_label' => 'Ifthenpay',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Integração Ifthenpay (yes/no)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'eupago',
                'vendus_field_label' => 'Eupago',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Integração Eupago (yes/no)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'print_discount',
                'vendus_field_label' => 'Imprimir Desconto',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Imprimir desconto no documento (yes/no)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'output',
                'vendus_field_label' => 'Saída',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Formato de saída (html, pdf)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'output_template_id',
                'vendus_field_label' => 'Template de Saída (ID)',
                'metadata_key' => null,
                'field_type' => 'number',
                'is_required' => false,
                'default_value' => null,
                'description' => 'ID do template de impressão',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'tx_id',
                'vendus_field_label' => 'Transação (TX ID)',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Identificador de transação',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'errors_full',
                'vendus_field_label' => 'Erros Detalhados',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => 'yes',
                'description' => 'Respostas de erro detalhadas (yes/no)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'rest_room',
                'vendus_field_label' => 'Sala (Restaurante)',
                'metadata_key' => null,
                'field_type' => 'number',
                'is_required' => false,
                'default_value' => null,
                'description' => 'ID da sala (restaurante)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'rest_table',
                'vendus_field_label' => 'Mesa (Restaurante)',
                'metadata_key' => null,
                'field_type' => 'number',
                'is_required' => false,
                'default_value' => null,
                'description' => 'ID da mesa (restaurante)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'occupation',
                'vendus_field_label' => 'Ocupação',
                'metadata_key' => null,
                'field_type' => 'number',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Número de pessoas/ocupação',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'stamp_retention_amount',
                'vendus_field_label' => 'Retenção – Selo (Valor)',
                'metadata_key' => null,
                'field_type' => 'number',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Montante de retenção de selo',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'irc_retention_id',
                'vendus_field_label' => 'Retenção – IRC (ID)',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Identificador de retenção IRC',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'mgmAmount',
                'vendus_field_label' => 'MGM Amount',
                'metadata_key' => null,
                'field_type' => 'number',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Montante MGM/gestão',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'related_document_id',
                'vendus_field_label' => 'Documento Relacionado (ID)',
                'metadata_key' => null,
                'field_type' => 'number',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Liga a outro documento por ID',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'return_qrcode',
                'vendus_field_label' => 'Retornar QRCode',
                'metadata_key' => null,
                'field_type' => 'boolean',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Retornar QRCode na resposta (1/0)',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'doc_to_generate',
                'vendus_field_label' => 'Documento a Gerar',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Força geração para tipo específico',
                'is_active' => true,
            ],
            // Campos de itens
            [
                'vendus_field' => 'item_reference',
                'vendus_field_label' => 'Item - Referência',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => true,
                'default_value' => null,
                'description' => 'Referência do produto lido do Excel',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'item_title',
                'vendus_field_label' => 'Item - Título',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => true,
                'default_value' => null,
                'description' => 'Nome/descrição do produto lido do Excel',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'item_quantity',
                'vendus_field_label' => 'Item - Quantidade',
                'metadata_key' => null,
                'field_type' => 'number',
                'is_required' => true,
                'default_value' => '1',
                'description' => 'Quantidade por linha da fatura',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'item_price',
                'vendus_field_label' => 'Item - Preço',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => true,
                'default_value' => null,
                'description' => 'Preço unitário (bruto) por item',
                'is_active' => true,
            ],
            [
                'vendus_field' => 'item_tax',
                'vendus_field_label' => 'Item - Imposto/IVA',
                'metadata_key' => null,
                'field_type' => 'string',
                'is_required' => false,
                'default_value' => null,
                'description' => 'Imposto/IVA aplicável (ex.: IVA 23%)',
                'is_active' => true,
            ],
        ];

        foreach ($defaults as $mapping) {
            self::firstOrCreate(
                ['vendus_field' => $mapping['vendus_field']],
                $mapping
            );
        }
        self::where('vendus_field', 'register_id')->delete();
    }

    public static function getByVendusField($field)
    {
        return self::where('vendus_field', $field)
            ->where('is_active', true)
            ->first();
    }
}